### ISSUE TITLE
We should allow fragment only URLs for in page navigation

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/viahtml#297]
Currently we make URLs absolute in the page as a security measure the reduce the attractiveness of Via as a platform for phishing. This is because although Via itself might be allowed, any URL to malware will be an absolute link and point back to the original content. This means Via can be used to potentially present a page to a user, but any links within that page will still run the risk of being listed in blocking services or caught by browser security measures etc.

One potential exception to this might be to allow fragment only links to allow in client navigation around the present page. These don't pose an obvious threat, and would help use things like tables of content.

See also:

 * https://github.com/hypothesis/product-backlog/issues/1307

## Implementation notes

* `viahtml.hooks.hooks.py:modify_tag_attrs()` - Contains the calls to make the anchor tags absolute
* `viahtml.context:make_absolute()` - Actually does it

Either of these places might be good places to add the behavior. `make_absolute()` is used in a few places, so it might be worth a short review of those to come to the best location.

**Comment by robertknight** [comment]
In addition to the Python code changes, there is also a frontend issue that needs fixing. See https://github.com/hypothesis/product-backlog/issues/1307#issuecomment-1027645926.

**Comment by robertknight** [comment]
Fixed via the merged PRs mentioned in this issue.
