### ISSUE TITLE
2nd canonical URL on https://cahier1939ms.github.io/texts/translation/ causes Hypothesis to commit incorrect document equivalence

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/viahtml#439]
### Steps to reproduce
1. Go to https://cahier1939ms.github.io/texts/translation/
2. Create annotation
3. note target URI (https://cahier1939ms.github.io/texts/translation/)
4. Open URL in Via
5. create annotation
6. note target URI (https://viahtml.hypothes.is/texts/translation/)

Seems to be due to:
<img width="524" alt="Screen Shot 2022-12-09 at 9 14 34 AM" src="https://user-images.githubusercontent.com/22603275/206727014-2c754b8a-5f09-4cd1-bb4e-f5b4fb3ab5a7.png">

### Expected behaviour
If possible we should see the canonical URL as https://cahier1939ms.github.io/texts/translation/.

### Additional details

 * https://hypothes-is.slack.com/archives/C2BLQDKHA/p1670592776889249

See also:

 * https://github.com/hypothesis/viahtml/issues/438

**Comment by jon-betts** [comment]
The first one is added by us in `viahtml`, the second is from the page and just happens to match the style of comments we have.

Of particular interest is fact this is a relative URL, we might have to handle that differently.

**Comment by darylhedley** [comment]
Support - can you update the customer that we won't be fixing this. However, if this comes up more we should revisit it.

Advice would be to make the link an absolute url.

**Comment by mkdir-washington-edu** [comment]
Closing per discussion above
